# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Skills"
  url = "#skills"
  weight = 15

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Work Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Courses"
  url = "#accomplishments"
  weight = 50
  
[[main]]
  name = "Blogs"
  url = "#posts"
  weight = 20


#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

[[main]]
  name = "Resume"
  url = "#"
  hasChildren = true

[[main]]
  parent = "Resume"
  name = "Webpage"
  url = "#"

[[main]]
  parent = "Resume"
  name = "PDF"
  url = "files/Tanmay_Chakrabarty_CV.pdf"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/Tanmay_Chakrabarty_CV.pdf"
#    weight = 70
